# Generated by Django 2.2.3 on 2019-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
