# Generated by Django 2.2.3 on 2019-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0002_text_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
