# Generated by Django 2.2.3 on 2019-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('here', '0003_text_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
